### ISSUE TITLE
"SchedulerType = ConcurrentDispatchQueueScheduler(qos: .background)" has crash

### ISSUE THREAD

**Issue by CoDancer** [mavlink/MAVSDK-Swift#132]
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

```
let drone = Drone.init(address: "", port: 8090)
drone.action.arm()
.andThen(drone.action.takeoff())
.subscribe(onCompleted: {
print("123")
}) { (error) in
print(error)
}
.dispose()

return true
}
```

but there has carsh in method of Drone init

**Comment by unipheas** [comment]
@CoDancer Can you explain what's going on in more detail please? Try to include any error messages or the steps to reproduce what you have found.

**Comment by CoDancer** [comment]
Thanks! There is  a project that I use the SDK, you can download and run the project, and you will see what I said.(The project url: https://github.com/CoDancer/MAVLinkSwiftDemo)

**Comment by unipheas** [comment]
@CoDancer It would really help us out if you can explain what's going on and try to give us more information. Providing a project isn't the ideal way to let us know what the exact issue is. Here are some links that can help you formulate an issue.

https://wiredcraft.com/blog/how-we-write-our-github-issues/
https://upthemes.com/blog/2014/02/writing-useful-github-issues/

Thank you!

**Comment by CoDancer** [comment]
@unipheas I just want to create an object of the drone in a method, so I use the "let drone = Drone.init(address: "", port: 8090)", but in the method of "public init(address: String,
                port: Int32,
                scheduler: SchedulerType = ConcurrentDispatchQueueScheduler(qos: .background))" has crash, 
<img width="2806" alt="WeChatdd0cd12daf609872b3b6e6c961473d85" src="https://user-images.githubusercontent.com/10137815/60024373-42d00500-96ca-11e9-9b59-984e517638a6.png">
like the image, and the debug is "Message from debugger: Terminated due to signal 9"

**Comment by JonasVautherin** [comment]
@CoDancer: Which version of MAVSDK-Swift do you use? Are you getting the frameworks through Carthage?

**Comment by CoDancer** [comment]
<img width="1226" alt="WeChat88dd22f1834a1707ab72e6cb2617e713" src="https://user-images.githubusercontent.com/10137815/60027782-b117c600-96d0-11e9-8193-2796cd5ab0c1.png">

**Comment by JonasVautherin** [comment]
Looks like your `Cartfile.resolved`, so I guess that's fine. I'll try to see if I can run your example. In the meantime, can you try our [example app](https://github.com/mavlink/MAVSDK-Swift-Example) and tell me if that fails as well?

**Comment by unipheas** [comment]
@CoDancer I had a look at your project. I can tell you that the reason it's crashing is because you do not have your storyboard view connected to your view controller class. That said, it looks like you're not even using it. So, unfortunately, it has nothing to do with the SDK itself but your app itself. I would suggest going through http://hackingwithswift.com/100 to get a better understanding of the iOS development environment.

**Comment by CoDancer** [comment]
@unipheas but I run my project if I shield the "Drone.init(address: "", port: 8090)",my project is normal.
like this.
<img width="589" alt="WeChatdb599e8f59a3430f5436a9d1a204f37d" src="https://user-images.githubusercontent.com/10137815/60070622-ee6c6a00-9749-11e9-853d-6dccbcfcf082.png">

**Comment by unipheas** [comment]
@CoDancer I'm playing around with your project. In the meantime can you please follow these [instructions](https://gist.github.com/unipheas/a5f94751c665995c56fba3c3af61a7a0#swift-available-for-macos).

**Comment by CoDancer** [comment]
@unipheas Do you mean this? Installation the QGroundControl on Mac.
<img width="932" alt="WeChat35211b8be4d965c148a184bada620335" src="https://user-images.githubusercontent.com/10137815/60072507-460dd400-9750-11e9-8326-96a7264bae70.png">
If so：
I had installed it.
<img width="994" alt="WeChat59331b87cb5446436dfe9ebc34993f55" src="https://user-images.githubusercontent.com/10137815/60072705-e663f880-9750-11e9-94c4-8a611b85c5f4.png">

**Comment by unipheas** [comment]
@CoDancer No. The Swift instructions at the bottom of that page, where the link directs too.

**Comment by unipheas** [comment]
@CoDancer By the way. Are you in China and do you have WeChat? I can speak with you directly on this if you'd like.

**Comment by CoDancer** [comment]
@unipheas  Ok, please add my Wechat,1848225396

**Comment by douglaswsilva** [comment]
I managed to get your project running. The reason for the crash I found was that you imported the libraries manually but didn't link them properly. To fix it, you can either add them to the **Embedded Binaries** or add a script to copy them during the build process in the **Build Phases**.

**Comment by douglaswsilva** [comment]
That being said, I don't think you need **Drone** folder in your project, since everything is already included in the Dronecode_SDK_Swift.framework.
Also, I know you did it for testing purposes, but I wouldn't call the actions inside app delegate, try to move that logic somewhere else. 

Good luck!
