### ISSUE TITLE
Dronecode still exists

### ISSUE THREAD

**Issue by unipheas** [mavlink/MAVSDK-Swift#150]
When creating the Carthage file and using `github "mavlink/MAVSDK-Swift" ~> 0.5.0` Dronecode_SDK_Swift.framework still exists. You will then need to `import Dronecode_SDK_Swift` in your code

**Comment by JonasVautherin** [comment]
Yes, because the renaming got finished when moving to [`0.6.0`](https://github.com/mavlink/MAVSDK-Swift/releases) :sweat_smile:. Is that an issue?

**Comment by unipheas** [comment]
Ah no, the README says to use 0.5.0. I'll upgrade and test again. I'll also update the readme. Sorry about that.
