### ISSUE TITLE
Can't build Mavsdk-Swift with the new Mavsdk-Proto

### ISSUE THREAD

**Issue by douglaswsilva** [mavlink/MAVSDK-Swift#152]
Repro Steps:
1. git clone https://github.com/mavlink/MAVSDK-Swift.git --recursive
2. bash tools/generate_from_protos.bash

Then try to open the project and compile.
Some of the enums will be empty + some other errors that will fail the build in the Mavsdk-swift project.

<img width="1440" alt="Screen Shot 2019-10-17 at 4 22 08 PM" src="https://user-images.githubusercontent.com/15242786/67040931-e8383a00-f0fa-11e9-8982-8b0e628b251e.png">

**Comment by JonasVautherin** [comment]
Yes, I can reproduce :confused:. Having a look.

**Comment by JonasVautherin** [comment]
I'll have to continue next week. What I changed fairly recently is that I added the documentation in the proto files. I'm wondering if that could be the root cause :confused:.

@unipheas: FYI, in case you also try to generate code :confused:.

**Comment by JonasVautherin** [comment]
Nevermind, I think I fixed it. @douglaswsilva would you mind reviewing the PR?
