### ISSUE TITLE
V2 Protocol Support

### ISSUE THREAD

**Issue by evilcap** [mavlink/MAVSDK-Swift#163]
Hello, are you considering mavlink v2 support?

**Comment by JonasVautherin** [comment]
MAVSDK is already supporting mavlink v2 (see [here](https://github.com/mavlink/MAVSDK/tree/develop/src/third_party/mavlink/include/mavlink)).

Is there something not working for you?

**Comment by evilcap** [comment]
Thanks for the information! Swift SDK also supports V2? On the official website of Mavlink support is not stated
