### ISSUE TITLE
Cannot find type 'GRPCCallHandler' in scope

### ISSUE THREAD

**Issue by seungbeom-son** [mavlink/MAVSDK-Swift#184]
I followed all steps. But when I tried to build my project, this error appeared.

**Cannot find type 'GRPCCallHandler' in scope**

Is there anything I missed?

<img width="419" alt="스크린샷 2021-02-23 오후 1 37 53" src="https://user-images.githubusercontent.com/40154993/108802805-67d1f500-75dc-11eb-86f4-fa48ecf7272c.png">

**Comment by julianoes** [comment]
@byuarus, @douglaswsilva, or @JonasVautherin?

**Comment by JonasVautherin** [comment]
Did you try to run the [example app](https://github.com/mavlink/mavsdk-swift-example) first? So that you could see how it is setup :+1:

**Comment by seungbeom-son** [comment]
> Did you try to run the [example app](https://github.com/mavlink/mavsdk-swift-example) first? So that you could see how it is setup 👍

Yes, I have already tried the example app. But the result was same.

**Comment by byuarus** [comment]
After updating MAVSDK-Swift in example app I see the same issue.
![Screen Shot 2021-02-23 at 9 29 50 AM](https://user-images.githubusercontent.com/10615444/108882877-b02beb80-75b9-11eb-99cf-ab286accbf75.png)

**Comment by JonasVautherin** [comment]
Hmm I don't understand, I just did it (updated [this line](https://github.com/mavlink/MAVSDK-Swift-Example/blob/master/project.yml#L11) to 0.10.0) and it works for me :confused:.

Did you guys run a clean build?

**Comment by JonasVautherin** [comment]
Ok I managed to reproduce it, let me have a look

**Comment by JonasVautherin** [comment]
@seungbeom-son: could you try with version 0.10.1?

**Comment by seungbeom-son** [comment]
> @seungbeom-son: could you try with version 0.10.1?

0.10.1 works well for me. Building the example app successfully completed. Thank you!!

However, another problem has occured 😭 

Whenever I tried to install the example app after build, Xcode shows 'Unable to install "MAVSDK_Swift_Example"' (No code signature found.). But I think this issue is not related to your SDK. I will try to fix this by myself.

Thank you. 😄

**Comment by JonasVautherin** [comment]
> (No code signature found.)

Doesn't it mean that you need to set the Team in the project settings?

**Comment by seungbeom-son** [comment]
> > (No code signature found.)
> 
> Doesn't it mean that you need to set the Team in the project settings?

Yes. I set the team in the project settings correctly.

I solved this problem in this way [https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/](url)
